const products = [
  // MÓDULOS
  {
    id: 1,
    name: "Módulo Samsung Galaxy A51",
    category: "modulos",
    price: 18500,
    brand: "Samsung",
    image: "assets/products/modules.jpg",
    badge: "Más vendido",
    description: "Pantalla AMOLED completa con marco. Original calidad A+.",
    stock: true,
  },
  {
    id: 2,
    name: "Módulo iPhone 11",
    category: "modulos",
    price: 32000,
    brand: "Apple",
    image: "assets/products/modules.jpg",
    badge: "Premium",
    description: "Pantalla LCD con digitalizador integrado. Compatible 100%.",
    stock: true,
  },
  {
    id: 3,
    name: "Módulo Motorola Moto G8 Plus",
    category: "modulos",
    price: 14200,
    brand: "Motorola",
    image: "assets/products/modules.jpg",
    badge: "",
    description: "Display IPS con táctil. Instalación sencilla plug & play.",
    stock: true,
  },
  {
    id: 4,
    name: "Módulo Xiaomi Redmi Note 10",
    category: "modulos",
    price: 16800,
    brand: "Xiaomi",
    image: "assets/products/modules.jpg",
    badge: "Oferta",
    description: "Pantalla AMOLED 6.43\" con digitalizador. Calidad original.",
    stock: true,
  },
  {
    id: 5,
    name: "Módulo Samsung Galaxy S21",
    category: "modulos",
    price: 42000,
    brand: "Samsung",
    image: "assets/products/modules.jpg",
    badge: "Premium",
    description: "Display Dynamic AMOLED 2X. Resolución FHD+ 120Hz.",
    stock: true,
  },
  {
    id: 6,
    name: "Módulo iPhone 13",
    category: "modulos",
    price: 55000,
    brand: "Apple",
    image: "assets/products/modules.jpg",
    badge: "Nuevo",
    description: "Super Retina XDR OLED. Sin necesidad de calibración.",
    stock: false,
  },

  // BATERÍAS
  {
    id: 7,
    name: "Batería Samsung Galaxy S20",
    category: "baterias",
    price: 6200,
    brand: "Samsung",
    image: "assets/products/batteries.jpg",
    badge: "",
    description: "4000 mAh. Con adhesivo incluido. Calidad original.",
    stock: true,
  },
  {
    id: 8,
    name: "Batería iPhone XR",
    category: "baterias",
    price: 8500,
    brand: "Apple",
    image: "assets/products/batteries.jpg",
    badge: "Más vendido",
    description: "2942 mAh. Ciclos de carga garantizados. Certificada.",
    stock: true,
  },
  {
    id: 9,
    name: "Batería Xiaomi Redmi Note 9",
    category: "baterias",
    price: 5100,
    brand: "Xiaomi",
    image: "assets/products/batteries.jpg",
    badge: "",
    description: "5020 mAh. Alta capacidad y larga duración.",
    stock: true,
  },
  {
    id: 10,
    name: "Batería Motorola G30",
    category: "baterias",
    price: 4800,
    brand: "Motorola",
    image: "assets/products/batteries.jpg",
    badge: "Oferta",
    description: "5000 mAh. Compatible también con Moto G20 y G10.",
    stock: true,
  },

  // CABLES
  {
    id: 11,
    name: "Cable USB-C a USB-C 100W",
    category: "cables",
    price: 2800,
    brand: "Universal",
    image: "assets/products/cables.jpg",
    badge: "Carga rápida",
    description: "Carga rápida 100W. 1.5m. Nylon trenzado resistente.",
    stock: true,
  },
  {
    id: 12,
    name: "Cable Lightning iPhone 20W",
    category: "cables",
    price: 3200,
    brand: "Apple",
    image: "assets/products/cables.jpg",
    badge: "",
    description: "Carga rápida compatible con todos los modelos iPhone.",
    stock: true,
  },
  {
    id: 13,
    name: "Flex de carga Samsung A32",
    category: "cables",
    price: 1900,
    brand: "Samsung",
    image: "assets/products/cables.jpg",
    badge: "",
    description: "Puerto de carga USB-C interno. Compatible A32 5G.",
    stock: true,
  },
  {
    id: 14,
    name: "Cable Micro USB 2.4A",
    category: "cables",
    price: 1500,
    brand: "Universal",
    image: "assets/products/cables.jpg",
    badge: "",
    description: "Carga y datos. Compatible con la mayoría de Android antiguos.",
    stock: true,
  },

  // REPUESTOS
  {
    id: 15,
    name: "Botón Home iPhone 7",
    category: "repuestos",
    price: 3500,
    brand: "Apple",
    image: "assets/products/repair.jpg",
    badge: "",
    description: "Con sensor Touch ID. Blanco o negro a elección.",
    stock: true,
  },
  {
    id: 16,
    name: "Speaker auricular Samsung A50",
    category: "repuestos",
    price: 2200,
    brand: "Samsung",
    image: "assets/products/repair.jpg",
    badge: "",
    description: "Parlante auricular superior. Calidad de sonido original.",
    stock: true,
  },
  {
    id: 17,
    name: "Cámara trasera Xiaomi Mi 11",
    category: "repuestos",
    price: 7800,
    brand: "Xiaomi",
    image: "assets/products/repair.jpg",
    badge: "Nuevo",
    description: "Triple cámara 108MP principal. Con flex incluido.",
    stock: true,
  },
  {
    id: 18,
    name: "Tapa trasera iPhone 12",
    category: "repuestos",
    price: 9200,
    brand: "Apple",
    image: "assets/products/repair.jpg",
    badge: "",
    description: "Vidrio trasero color negro. Con adhesivo de instalación.",
    stock: false,
  },

  // ACCESORIOS
  {
    id: 19,
    name: "Vidrio templado iPhone 14 Pro",
    category: "accesorios",
    price: 1800,
    brand: "Apple",
    image: "assets/products/accessories.jpg",
    badge: "Pack x2",
    description: "9H dureza. Anti-huella. Instalación sin burbujas.",
    stock: true,
  },
  {
    id: 20,
    name: "Vidrio templado Samsung A54",
    category: "accesorios",
    price: 1600,
    brand: "Samsung",
    image: "assets/products/accessories.jpg",
    badge: "",
    description: "Cobertura total pantalla. Compatible con funda.",
    stock: true,
  },
  {
    id: 21,
    name: "Cargador Samsung 25W Original",
    category: "accesorios",
    price: 5500,
    brand: "Samsung",
    image: "assets/products/accessories.jpg",
    badge: "Original",
    description: "Super Fast Charging 25W. Compatible S20, S21, A52 y más.",
    stock: true,
  },
  {
    id: 22,
    name: "Auriculares Tipo C Samsung",
    category: "accesorios",
    price: 2900,
    brand: "Samsung",
    image: "assets/products/accessories.jpg",
    badge: "",
    description: "In-ear con micrófono. Compatible con todos los USB-C.",
    stock: true,
  },
];

const services = [
  {
    id: 1,
    icon: "📱",
    name: "Cambio de Pantalla",
    description: "Reemplazamos tu display roto o sin imagen. Trabajamos con pantallas originales y de alta calidad.",
    priceFrom: 8000,
    time: "1-2 hs",
    popular: true,
  },
  {
    id: 2,
    icon: "🔋",
    name: "Cambio de Batería",
    description: "Tu batería ya no dura? La cambiamos por una nueva con garantía de 6 meses.",
    priceFrom: 3500,
    time: "30 min",
    popular: false,
  },
  {
    id: 3,
    icon: "⚡",
    name: "Reparación Puerto de Carga",
    description: "Solucionamos problemas de carga, ya sea limpieza, flex o conector dañado.",
    priceFrom: 2500,
    time: "1 hs",
    popular: false,
  },
  {
    id: 4,
    icon: "💾",
    name: "Recuperación de Datos",
    description: "Recuperamos fotos, contactos y archivos de celulares dañados o mojados.",
    priceFrom: 5000,
    time: "24-48 hs",
    popular: false,
  },
  {
    id: 5,
    icon: "📷",
    name: "Reparación de Cámara",
    description: "Cambiamos módulos de cámara dañados. Fotos nítidas como el primer día.",
    priceFrom: 4000,
    time: "1-2 hs",
    popular: false,
  },
  {
    id: 6,
    icon: "🔓",
    name: "Liberación de Equipo",
    description: "Liberamos tu celular para usarlo con cualquier compañía. Rápido y seguro.",
    priceFrom: 1500,
    time: "30 min",
    popular: false,
  },
];

const brands = [
  { name: "Samsung", logo: "Samsung" },
  { name: "Apple", logo: "Apple" },
  { name: "Motorola", logo: "Motorola" },
  { name: "Xiaomi", logo: "Xiaomi" },
  { name: "LG", logo: "LG" },
  { name: "Huawei", logo: "Huawei" },
  { name: "Nokia", logo: "Nokia" },
  { name: "Oppo", logo: "Oppo" },
];

const testimonials = [
  {
    name: "Lucas M.",
    avatar: "LM",
    rating: 5,
    text: "Llevé mi Samsung A51 con la pantalla rota y en menos de 2 horas estaba como nuevo. Muy buena atención y precio justo.",
    service: "Cambio de Pantalla",
  },
  {
    name: "Valentina R.",
    avatar: "VR",
    rating: 5,
    text: "Compré el módulo para mi iPhone y llegó perfecto, bien embalado. La instalación fue sencilla con el tutorial que me mandaron por WhatsApp.",
    service: "Compra de Módulo",
  },
  {
    name: "Marcos P.",
    avatar: "MP",
    rating: 5,
    text: "Excelente atención! Recuperaron todos mis fotos de un teléfono mojado. Pensé que los había perdido para siempre. 100% recomendable.",
    service: "Recuperación de Datos",
  },
  {
    name: "Sofía G.",
    avatar: "SG",
    rating: 4,
    text: "Muy buena variedad de repuestos a precios razonables. Envío rápido y bien protegido. Volvería a comprar sin dudas.",
    service: "Compra Online",
  },
];
